### ISSUE TITLE
str(self.ipv4_address) returns a 4 byte array, which is an IPv4 address in binary.

### ISSUE THREAD

**Issue by jeffsilverm** [jeffsilverm/nbmdt#11]
`ping: b'\xc0\xa8\x00\x01': Name or service not known
Traceback (most recent call last):
  File "/home/jeffs/nbmdt/nbmdt.py", line 179, in <module>
    if current_system.default_ipv4_gateway.ping4():
  File "/home/jeffs/python/nbmdt/network.py", line 134, in ping4
    raise DNSFailure
network.DNSFailure`

0xc0 is 192 and 0xa8 is 168 .  0x01 is one, thus this is 192.168.0.1

I suspect that the problem is in the __str__ method in <class 'network.IPv4Address'> .

**Comment by jeffsilverm** [comment]
I was wrong.  I was trying to str(self.ipv4_address) when I should have done str(self).  self.ipv4_address is a byte array, and its __str__() method is to return a byte string.  The __str__() method I wrote for IPv4Address objects returns a (Unicode) string.

**Comment by jeffsilverm** [comment]
Exception is no longer throw.
