### ISSUE TITLE
ip command is in different places in native Ubuntu and WSL.  Also ip command output different on WSL

### ISSUE THREAD

**Issue by jeffsilverm** [jeffsilverm/nbmdt#13]
On native windows:

    C:\Users\jeffs>python
    Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import platform
    >>> h=platform.uname()
    >>> print(h)
    uname_result(system='Windows', node='Jeffs-Win-10-laptop', release='10', version='10.0.17063', machine='AMD64', processor='Intel64 Family 6 Model 69 Stepping 1, GenuineIntel')
    >>>

On Windows Services linux:

    >>> import platform
    >>> h=platform.uname()
    >>> print(h)
    uname_result(system='Linux', node='Jeffs-Win-10-laptop', release='4.4.0-17063-Microsoft', version='#1000-Microsoft Thu Jan 01  PST 2016', machine='x86_64', processor='x86_64')
    >>>
    (general) jeffs@Jeffs-Win-10-laptop:~/ubuntu/python/nbmdt$ whereis ip
    ip: /bin/ip /sbin/ip /usr/share/man/man7/ip.7.gz /usr/share/man/man8/ip.8.gz
    (general) jeffs@Jeffs-Win-10-laptop:~/ubuntu/python/nbmdt$

There is a problem with the output of the ip command on windows services linux (WSL) 

    (general) jeffs@Jeffs-Win-10-laptop:~/ubuntu/python/nbmdt$ python3 nbmdt.py
    socket.gethostbyaddr raised an exception on none, continuing
    Tried to add the destination none to a route, and a socket.gaierror exception was raised
    Traceback (most recent call last):
    File "nbmdt.py", line 172, in <module>
        current_system = SystemDescription()
      File "nbmdt.py", line 110, in __init__
        self.ipv4_routes = network.IPv4Route.find_ipv4_routes()
      File "/mnt/c/Users/jeffs/ubuntu/python/nbmdt/network.py", line 392, in find_ipv4_routes
        route[fields[i]] = fields[i+1]    
    IndexError: list index out of range

    (general) jeffs@Jeffs-Win-10-laptop:~/ubuntu/python/nbmdt$
    (general) jeffs@Jeffs-Win-10-laptop:~/ubuntu/python/nbmdt$ ip route list
    none 224.0.0.0/4 dev eth0  proto none  metric 256
    none 255.255.255.255 dev eth0  proto none  metric 256
```
none 224.0.0.0/4 dev eth1  proto none  metric 256
none 255.255.255.255 dev eth1  proto none  metric 256
none 127.0.0.0/8 dev lo  proto none  metric 256
none 127.0.0.1 dev lo  proto none  metric 256
none 127.255.255.255 dev lo  proto none  metric 256
none 224.0.0.0/4 dev lo  proto none  metric 256
none 255.255.255.255 dev lo  proto none  metric 256
none default via 192.168.0.1 dev wifi0  proto none  metric 0
none 192.168.0.0/24 dev wifi0  proto none  metric 256
none 192.168.0.7 dev wifi0  proto none  metric 256
none 192.168.0.255 dev wifi0  proto none  metric 256
none 224.0.0.0/4 dev wifi0  proto none  metric 256
none 255.255.255.255 dev wifi0  proto none  metric 256
none 224.0.0.0/4 dev wifi1  proto none  metric 256
none 255.255.255.255 dev wifi1  proto none  metric 256
none 224.0.0.0/4 dev wifi2  proto none  metric 256
none 255.255.255.255 dev wifi2  proto none  metric 256
(general) jeffs@Jeffs-Win-10-laptop:~/ubuntu/python/nbmdt$

```

On Fedora:

**Comment by jeffsilverm** [comment]
Created a method in configuration.py, find_executable, that locates executables in various places it is likely to be.
