### ISSUE TITLE
Circular import

### ISSUE THREAD

**Issue by jeffsilverm** [jeffsilverm/nbmdt#29]
There is a circular import

```
ImportError while importing test module '/home/jeffs/python/nbmdt/test/test_utilities.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_utilities.py:12: in <module>
    import utilities
utilities.py:13: in <module>
    from nbmdt import SystemDescription
nbmdt.py:21: in <module>
    import datalink  # OSI layer 2: # Media Access Control: arp, ndp
datalink.py:14: in <module>ImportError while importing test module '/home/jeffs/python/nbmdt/test/test_utilities.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_utilities.py:12: in <module>
    import utilities
utilities.py:13: in <module>
    from nbmdt import SystemDescription
nbmdt.py:21: in <module>
    import datalink  # OSI layer 2: # Media Access Control: arp, ndp
datalink.py:14: in <module>
    from interface import Interface
interface.py:12: in <module>
    from utilities import OsCliInter, os_name, the_os
E   ImportError: cannot import name 'OsCliInter'

    from interface import Interface
interface.py:12: in <module>
    from utilities import OsCliInter, os_name, the_os
E   ImportError: cannot import name 'OsCliInter'
```

**Comment by jeffsilverm** [comment]
There is another problem, this time with OsCliInter:
```
effs@jeffs-desktop:/home/jeffs/python/nbmdt  (development) *  $ python3 nbmdt.py
Testing the __file__ special variable: /home/jeffs/python/nbmdt/application.py
Traceback (most recent call last):
  File "nbmdt.py", line 16, in <module>
    import utilities
  File "/home/jeffs/python/nbmdt/utilities.py", line 13, in <module>
    from nbmdt import SystemDescription
  File "/home/jeffs/python/nbmdt/nbmdt.py", line 22, in <module>
    import datalink  # OSI layer 2: # Media Access Control: arp, ndp
  File "/home/jeffs/python/nbmdt/datalink.py", line 14, in <module>
    from interface import Interface
  File "/home/jeffs/python/nbmdt/interface.py", line 12, in <module>
    from utilities import OsCliInter, os_name, the_os
ImportError: cannot import name 'OsCliInter'
jeffs@jeffs-desktop:/home/jeffs/python/nbmdt  (development) *  $ 

```


```
jeffs@jeffs-desktop:/home/jeffs/python/nbmdt  (development) *  $ fgrep OsCliInter *.py */*.py
application.py:            apps_str: str = utilities.OsCliInter.run_command(["ps", "-ax"])
datalink.py:from utilities import OsCliInter, os_name, the_os
datalink.py:            datalinks_str: str = OsCliInter.run_command(cls.DISCOVER_ALL_DATALINKS_COMMAND)
datalink.py:            raise NotImplemented(f"{OsCliInter.system} is not implemented yet in DataLink")
guts_of_interface.py:        lnk_str: str = OsCliInter.run_command(PhysicalLink.DISCOVER_LINK_COMMAND)
guts_of_interface.py:            raise NotImplemented(f"{OsCliInter.system} is not implemented yet in PhysicalLink")
guts_of_interface.py:            raise NotImplementedError(f"In DataLink.discover, {OsCliInter.system} is not implemented")
guts_of_interface.py:        lnk_str:str = OsCliInter.run_command(cls.DISCOVER_ADDR_COMMAND )
interface.py:from utilities import OsCliInter, os_name, the_os
interface.py:        results = OsCliInter.run_command([Interface.IP_COMMAND, "link", "list"])
physical.py:        results = utilities.OsCliInter.run_command(command=command)
physical.py:        if "linux" == utilities.OsCliInter.system:
physical.py:        elif "windows" == utilities.OsCliInter.system:
physical.py:        elif 'darwin' == utilities.OsCliInter.system:
physical.py:        elif 'java' == utilities.OsCliInter.system:
physical.py:    results_xml:str = utilities.OsCliInter.run_command(command=command)
utilities.py:class OsCliInter(object):
utilities.py:    # Since the system is going to be the same across the entire program, populate it when the OsCliInter object is
utilities.py:    # imported for the first time and then make it available to any object in class OsCliInter (which should not need
utilities.py:# of class OsCliInter or else the compiler will raise a NameError exception at compile time
utilities.py:os_name: str = OsCliInter.system.lower()
utilities.py:        print(f"In linux, the uname -a command output is \n{OsCliInter.run_command(['uname', '-a'])}\n.")
test/test_interface.py:@patch("utilities.OsCliInter.run_command")
test/test_interface.py:@patch("utilities.OsCliInter.run_command")
test/test_interface.py:@patch("utilities.OsCliInter.run_command")
test/test_interface.py:@patch("utilities.OsCliInter.run_command")
test/test_interface.py:@patch("utilities.OsCliInter.run_command")
jeffs@jeffs-desktop:/home/jeffs/python/nbmdt  (development) *  $ 
```

Resolve Issue 29 before proceeding.

**Comment by jeffsilverm** [comment]
The easy way to test this is to have utilities.py run by itself.
```
    jeffs@evil-kali:~/nbmdt$ python3 utilities.py 
    Enter an issue that I changed the values of the constants from integers to strings for reliability
    Traceback (most recent call last):
      File "utilities.py", line 14, in <module>
        import application
      File "/home/jeffs/nbmdt/application.py", line 20, in <module>
        import utilities
      File "/home/jeffs/nbmdt/utilities.py", line 16, in <module>
        import datalink
      File "/home/jeffs/nbmdt/datalink.py", line 15, in <module>
        from utilities import OsCliInter, os_name, the_os
    ImportError: cannot import name 'OsCliInter' from 'utilities' (/home/jeffs/nbmdt/utilities.py)
    jeffs@evil-kali:~/nbmdt$ 
```
Why is this happening?

    jeffs@evil-kali:~/nbmdt$ fgrep OsCliInter utilities.py 
    class OsCliInter(object):
    # Since the system is going to be the same across the entire program, populate it when the OsCliInter object is
    # imported for the first time and then make it available to any object in class OsCliInter (which should not need
    # of class OsCliInter or else the compiler will raise a NameError exception at compile time
    os_name: str = OsCliInter.system.lower()
            print(f"In linux, the uname -a command output is \n{OsCliInter.run_command(['uname', '-a'])}\n.")
    jeffs@evil-kali:~/nbmdt$ 
Figure out to import an inner class
