### ISSUE TITLE
nbmdt fails when creating object applications

### ISSUE THREAD

**Issue by jeffsilverm** [jeffsilverm/nbmdt#32]
```
jeffs@jeffs-desktop:/home/jeffs/python/nbmdt  (development) *  $ ls *.json
desktop_network_before.json  jeffs-desktop.json  mock_nbmdt_config.json  network_fixed.json                    xyzzy.json
desktop_network.json         lshw.json           network_broken.json     nominal_test_nbmt_configuration.json
jsons@jeffs-desktop:/home/jeffs/python/nbmdt  (development) *  $ python3 nbmdt.py --nominal nominal_test_nbmt_configuration.j
Testing the __file__ special variable: /home/jeffs/python/nbmdt/utilities.py
Testing the __file__ special variable: nbmdt.py
Traceback (most recent call last):
  File "nbmdt.py", line 255, in <module>
    main()
  File "nbmdt.py", line 79, in main
    current_system: utilities.SystemDescription = utilities.SystemDescription.discover()
  File "/home/jeffs/python/nbmdt/utilities.py", line 120, in discover
    applications: typing.Dict = application.Application.discover()
NameError: name 'application' is not defined
jeffs@jeffs-desktop:/home/jeffs/python/nbmdt  (development) *  $ ls application.py 
application.py
jeffs@jeffs-desktop:/home/jeffs/python/nbmdt  (development) *  $ fgrep "class " application.py
# Contains a class for applications and a class for DNS, which is an application
class Application(object):
class DNSFailure(Exception):
class DNS(object):
class Web(object):
jeffs@jeffs-desktop:/home/jeffs/python/nbmdt  (development) *  $ 

```

Investigate typing and circular imports

**Comment by jeffsilverm** [comment]
Might be redundant with Issue 29.
